services:
  postgres:
    container_name: courses-db
    image: postgres:14
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    networks:
      - corporate-network
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DATABASE_USER}", "-d", "${DATABASE_NAME}"]
      interval: 1m
      retries: 3
      start_period: 5s
      timeout: 5s

  api:
    image: courses-api:1.0.0
    container_name: api
    env_file:
      - .env
    build:
      dockerfile: dev.dockerfile
      context: .
    depends_on:
      - postgres
    networks:
      - corporate-network
    ports:
      - "8080:8080"

networks:
  corporate-network:
      driver: bridge

volumes:
  db-data: